### ISSUE TITLE
[ERROR] Library not working in Windows

### ISSUE THREAD

**Issue by WaterKnight1998** [rbnvrw/nd2reader#41]
I have tried to import your library in Windows and I am getting following error:

```
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nd2reader import ND2Reader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\nd2reader\__init__.py", line 2, in <module>
    from nd2reader.reader import ND2Reader
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\nd2reader\reader.py", line 1, in <module>
    from pims import Frame
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\pims\__init__.py", line 1, in <module>
    from pims.api import *
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\pims\api.py", line 113, in <module>
    from pims_nd2 import ND2_Reader as ND2Reader_SDK
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\pims_nd2\__init__.py", line 1, in <module>
    from .nd2reader import ND2_Reader
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\pims_nd2\nd2reader.py", line 8, in <module>
    from . import ND2SDK as h
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\pims_nd2\ND2SDK.py", line 22, in <module>
    nd2 = cdll.LoadLibrary(os.path.join(dlldir, 'v6_w32_nd2ReadSDK.dll'))
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by ggirelli** [comment]
Hi there! *(I am not the maintainer of this repo, just thought maybe I could help you out here)*

It looks like something wrong with the installation of the `pims` dependency, like a dll (`v6_w32_nd2ReadSDK.dll`) is probably missing.

Does the same error show up if you run the following?

```
from pims import Frame
```

I googled around a bit, and I found [this possible solution on StackOverflow](https://stackoverflow.com/a/59537544). Let me know if this helps!

**Comment by rbnvrw** [comment]
Thanks for weighing in @ggirelli and thank you for the bug report @WaterKnight1998 

The relevant line in the error is here: `from pims.api import *` followed by `from pims_nd2 import ND2_Reader as ND2Reader_SDK`.

Pims is trying to import the `pims_nd2` module that you have installed. [This is a different library which uses the Nikon SDK](https://github.com/soft-matter/pims_nd2). I see that in the mean time you have submitted a report there: https://github.com/soft-matter/pims_nd2/issues/22. 

Alternatively, you could try to use this library, which means you'll first have to remove `pims_nd2` so pims is no longer trying to load it. I'll now close this.
